### PR TITLE
Gac 005 liu yangs branch GACagent Class

### PR DESCRIPTION
**Pull request by LiuYangMage**
Take a look....

### CODE REVIEW

**Review by axlbrown — APPROVED** [review]
lgtm
I think whether the rest of the training is in main.py or agent.py makes little difference now because we already have a very good idea of what left to be done. And it will not grow very big hopefully.

**Review by axlbrown — APPROVED** [review]
good catch

**Review by gwbcho — APPROVED** [review]
Aside from those changes which I recommended (which I believe you've already applied) I think this looks good at this time. Again, since we aren't testing anything we won't actually know if you made any mistakes until we actually run, train, and assess the program... Which makes me nervous.

**Comment by LiuYangMage** [comment]
@gwbcho Don't worry. We will sit down and go through the code line by line together, so that everyone knows everything  and we can makes sure we are consistent with the paper.
My experience is that, it's hard to find a bug by testing a single function/class, since usually it's not gramma bug, but mathematical bug.

**Pull request merged**
