### PR TITLE
Add training functionalities to the Value network

### PR DESCRIPTION
**Pull request by axlbrown**
Define a training graph inside the Value class itself such that it simplifies the overall training loop.

### CODE REVIEW

**Review by gwbcho — COMMENTED** [review]
What's the objective of this changes set? Is it just to reduce the clutter in the generative class?

**Comment by axlbrown** [comment]
That's right. It's basically a clear implementation of line 13-15 of
Algorithm 2.

**Comment by gwbcho** [comment]
Sounds good, you may need to review some minor changes I made to your branch just now to resolve some conflicts. Just pull the most recent version onto your local environment.

You should probably do a git fetch -a followed by git rebase origin/master before merging just to be doubly sure this is all good (use git push origin -f after rebasing). Sorry for the inconvenience man.

**Review by gwbcho — APPROVED** [review]

**Comment by axlbrown** [comment]
> Sounds good, you may need to review some minor changes I made to your branch just now to resolve some conflicts. Just pull the most recent version onto your local environment.
> 
> You should probably do a git fetch -a followed by git rebase origin/master before merging just to be doubly sure this is all good (use git push origin -f after rebasing). Sorry for the inconvenience man.

No worries. Let me try.

**Review by baijiuyang — APPROVED** [review]

**Pull request merged**
