### PR TITLE
Add cmd options and a gitignore file

### PR DESCRIPTION
**Pull request by axlbrown**
Basically copying the original, with minor changes to option names to make them easier to understand hopefully.

### CODE REVIEW

**Comment by gwbcho** [comment]
There was some other functionality on the page right? Will you be implementing those lines of code or are you waiting on the rest of us to finish our given sections? I think that most if not all function and class signatures should be the same. Though, their locations may differ based on their responsibilities.

**Comment by gwbcho** [comment]
Otherwise I'd say this looks good.

**Comment by axlbrown** [comment]
> There was some other functionality on the page right? Will you be implementing those lines of code or are you waiting on the rest of us to finish our given sections? I think that most if not all function and class signatures should be the same. Though, their locations may differ based on their responsibilities.

I'm not waiting. Which page are you referring to?

**Comment by gwbcho** [comment]
I was just referencing the lines below the CLI elements. Lines 61 onwards in the original code.

**Review by gwbcho — APPROVED** [review]
Are we going to be leaving lines 61 onwards till later? I'm fine if we are, just want to clarify.

**Comment by axlbrown** [comment]
> I was just referencing the lines below the CLI elements. Lines 61 onwards in the original code.

Got you. Yes, I'll implement the other stuff in that file as well. I'll do it in my next branch.

**Review by baijiuyang — APPROVED** [review]
Looks good to me

**Comment by LiuYangMage** [comment]
Looks good!

**Pull request merged**
